version: '3.9'

services:
  kafka:
    container_name: play-scala-kafka-kafka
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_MAX_MESSAGE_BYTES=20000000
    networks:
      - app-tier

  kafka-init-topics:
    image: 'bitnami/kafka:latest'
    command: "/opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic play-scala-kafka-topic"
    depends_on:
      kafka:
        condition: service_started
    networks:
      - app-tier

  app:
    container_name: play-scala-kafka-app
    build:
      context: ..  # Use parent directory as context
      dockerfile: Docker/Dockerfile
    restart: always
    depends_on:
      kafka-init-topics:
        condition: service_completed_successfully
    ports:
      - 9000:9000
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  kafka_data:
    driver: local